[package]
name = "service-binding"
version = "0.2.0"
edition = "2021"
authors = ["Wiktor Kwapisiewicz <wiktor@metacode.biz>"]
description = "Automates parsing and binding to TCP and Unix sockets"
repository = "https://github.com/wiktor-k/service-binding"
license = "MIT OR Apache-2.0"
keywords = ["sockets", "parsing"]
categories = ["parsing"]
exclude = [".github"]

[dev-dependencies]
actix-web = "4"
clap = { version = "3.1", features = ["derive", "env"] }
