name: CI

on: [push, pull_request]

jobs:
  # Use the following command to fix words locally:
  # codespell --ignore-words-list "ser,crate,daa,keypair" --skip "*/target,*-sys" --write-changes
  check-spelling:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
      - name: Check spelling
        uses: codespell-project/actions-codespell@master
        with:
          ignore_words_list: "ser,crate,daa,keypair"
          path: tss-esapi
          skip: "*/target,*-sys"

  formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check formatting
        run: cargo fmt --all -- --check

  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: cargo build --verbose --all && cargo test --verbose --all

  lints:
    name: Clippy lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for lints
        run: cargo clippy -- -D warnings
